# Generated by Django 4.0 on 2021-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/examples/'),
        ),
    ]
