# Generated by Django 4.0 on 2021-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_example_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='example_image',
            field=models.ImageField(default=1, upload_to='posts/images/2021/12/11'),
            preserve_default=False,
        ),
    ]
