# Generated by Django 4.0 on 2021-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_example_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='example_image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/images/%Y/%m/%d', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
