# Generated by Django 3.2.8 on 2021-12-27 10:50

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_content_alter_post_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='posts/images/%Y/%m/%d', width_field='image_width'),
        ),
    ]
