# Generated by Django 4.0 on 2021-12-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_created_author_modified_book_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
