# Generated by Django 4.0 on 2021-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_author_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/books/covers/%Y/%m/%d'),
        ),
    ]
