# Generated by Django 3.2.8 on 2021-12-27 11:00

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20211222_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='books/covers/%Y/%m/%d'),
        ),
    ]
